### ISSUE TITLE
Input Data File for MD1.f90

### ISSUE THREAD

**Issue by Darkboson** [itamblyn/FORTRAN#1]
Hello itamblyn, a fellow FORTRAN Coder here, could you please provide me with a copy of the input file which you had used for the initialization of the program, I am unable to achieve complete program execution and I believe it may be due to an error on my part regarding the input file. Thank you

**Comment by itamblyn** [comment]
Compile it and change the permissions to allow execution

```gfortran md1.f90 -o md1.x; chmod u+x md1.x```

You should be able to pipe the necessary input strings with the file `control.in`

```./md1.x < control.in```

In that file you will see a list of parameters the code needs to run. 

They are actually defined within the source code:

read(*,'(a)',end=200,err=800) title
read(*,'(a)',end=200,err=800) SampIn
read(*,'(a)',end=200,err=800) SampOut
read(*,  *  ,end=200,err=800) Nsteps
read(*,  *  ,end=200,err=800) deltat
read(*,  *  ,end=200,err=800) RhoRequested
read(*,  *  ,end=200,err=800) TRequested

The file `coor.in` within that directory shows the correct input format for the particles.
